Repository nasa/stitchee, pull requests merged in 2024-05, with the labels that each got.

#180 propagate first empty file if all input files are empty
  CHANGELOG.md
  concatenator/dataset_and_group_handling.py
  tests/data/unit-test-data/TEMPO_NO2_L2_V03_20240328T154353Z_S008G01.nc4
  tests/unit/test_dataset_and_group_handling.py
Labels: enhancement

#187 Feature/issue 133 add readthedocs
  .github/dependabot.yml
  .github/workflows/pr-rtd-link.yml
  .readthedocs.yaml
  CHANGELOG.md
  README.md
  concatenator/attribute_handling.py
  mkdocs.yml
  poetry.lock
  pyproject.toml
Labels: documentation

#188 issue-133 again - add missing index.md and styles.css
  docs/css/styles.css
  docs/index.md
  mkdocs.yml
Labels: bug, documentation

#189 Feature/issue 181 add argument to change group delimiter
  CHANGELOG.md
  README.md
  concatenator/__init__.py
  concatenator/attribute_handling.py
  concatenator/dataset_and_group_handling.py
  concatenator/run_stitchee.py
  concatenator/stitchee.py
  tests/test_concat.py
Labels: enhancement

#190 Feature/issue 134 expand tests with output from subsetter
  .codecov.yml
  .github/workflows/integration-test.yml
  .github/workflows/run_tests.yml
  CHANGELOG.md
  concatenator/attribute_handling.py
  concatenator/run_stitchee.py
  poetry.lock
  pyproject.toml
  scripts/create-netrc
  tests/integration/__init__.py
  tests/integration/test_concat_with_subsetting_first.py
  tests/integration/test_history_construction.py
  tests/local/__init__.py
  tests/local/test_stitchee_with_local_files.py
  tests/unit/test_attribute_handling.py
  tests/unit/test_cli.py
  tests/unit/test_dataset_and_group_handling.py
  tests/unit/test_file_ops.py
  tests/unit/test_group_handling.py
Labels: testing
