Repository nasa/stitchee, pull requests merged in 2024-04, with the labels that each got.

#158 add pypi publishing steps to build-pipeline.yml
  .github/workflows/build-pipeline.yml
  CHANGELOG.md
Labels: automation

#177 Feature/issue 176 resolve linting error
  .github/workflows/run_tests.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  concatenator/stitchee.py
Labels: bug

#179 Feature/issue 170 add badges to readme
  CHANGELOG.md
  README.md
Labels: documentation

#178 removing compression for string array of small size
  .github/workflows/release-created.yml
  CHANGELOG.md
  concatenator/dataset_and_group_handling.py
Labels: enhancement
